[package]
name = "rust-nn"
version = "0.1.0"
authors = ["TheTazza <teo@promaton.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
ndarray-rand = "0.11"

rust-mnist = "0.1"
rand = "0.7"